import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, Shield, AlertTriangle, CheckCircle2 } from 'lucide-react';

const sections = [
  { title: '1. Acceptance of Terms', body: 'By accessing and using Tooler ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the Service.' },
  { title: '2. Description of Service', body: 'Tooler provides free, web-based calculators, converters, and utility tools including but not limited to age calculators, financial planners, health calculators, QR code generators, image tools, and URL shorteners. All tools are provided for informational and educational purposes only.' },
  { title: '3. Fair Use of Calculators and Converters', body: 'You agree to use the calculators and converters responsibly. The tools are designed for personal, non-commercial use. You may not: (a) attempt to overload or crash the Service, (b) use automated scripts to abuse the URL shortener or other resources, (c) redistribute or resell access to the tools, or (d) use the tools for any unlawful purpose.' },
  { title: '4. No Warranties', body: 'The Service and all tools are provided "AS IS" and "AS AVAILABLE" without warranties of any kind, either express or implied. We do not guarantee that the calculators will be accurate, complete, or reliable. You are solely responsible for any decisions made based on the results produced by the tools.' },
  { title: '5. Disclaimer of Liability', body: 'To the maximum extent permitted by law, Tooler and its contributors shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of—or inability to use—the Service. This includes but is not limited to financial decisions made using the SIP or BMI calculators, or data loss from image conversion tools.' },
  { title: '6. User Accounts', body: 'Certain features may require you to create an account. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account. We reserve the right to suspend or terminate accounts that violate these Terms.' },
  { title: '7. Third-Party Services', body: 'Some tools integrate with third-party services (e.g., TinyURL for link shortening). We are not responsible for the availability, accuracy, or practices of these external services. Use of third-party services is subject to their respective terms.' },
  { title: '8. Intellectual Property', body: 'All content, design, and code on Tooler are the property of Tooler unless otherwise stated. You may not copy, modify, or distribute the Service without permission. Output generated by the tools (QR codes, converted files, shortened URLs) belongs to you.' },
  { title: '9. Changes to These Terms', body: 'We may update these Terms of Service from time to time. Changes will be posted on this page with an updated revision date. Continued use of the Service after changes constitutes acceptance of the new terms.' },
  { title: '10. Contact', body: 'If you have questions about these Terms, you can reach us through our Contact Us page or the Feedback form. We aim to respond to all inquiries within a reasonable timeframe.' },
];

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 py-8 sm:py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link to="/" className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-6 transition-colors">
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Home</span>
        </Link>

        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 bg-primary-100 rounded-full px-4 py-2 text-sm font-medium text-primary-700 mb-4">
            <FileText className="w-4 h-4" />
            <span>Legal</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-3">Terms of Service</h1>
          <p className="text-gray-600">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 sm:p-8 mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Shield className="w-5 h-5 text-primary-600" />
            <h2 className="text-lg font-semibold text-gray-900">Summary at a Glance</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex items-start gap-3"><CheckCircle2 className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" /><p className="text-sm text-gray-700">All tools are free for personal, non-commercial use.</p></div>
            <div className="flex items-start gap-3"><CheckCircle2 className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" /><p className="text-sm text-gray-700">Output files (QR codes, PDFs, images) belong to you.</p></div>
            <div className="flex items-start gap-3"><AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" /><p className="text-sm text-gray-700">Results are for informational purposes, not professional advice.</p></div>
            <div className="flex items-start gap-3"><AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" /><p className="text-sm text-gray-700">We are not liable for decisions made using the tools.</p></div>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 sm:p-8">
          <div className="space-y-8">
            {sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-lg font-semibold text-gray-900 mb-2">{section.title}</h2>
                <p className="text-gray-600 leading-relaxed">{section.body}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-8 text-center">
          <p className="text-sm text-gray-500">Questions about these terms? <Link to="/contact" className="text-primary-600 hover:text-primary-700 font-medium">Contact us</Link></p>
        </div>
      </div>
    </div>
  );
}
